### PR TITLE
finish system requirements

### LINKED ISSUE #94: Write System Concept
Subtasks:
- [x] #95
- [x] #97
- [x] #96
- [x] #98

### LINKED ISSUE #98: Write System Concept - System Requirements and Specifications

### PR DESCRIPTION
**Pull request by dyc3**
closes #98
closes #94

### CODE REVIEW

**Comment by dyc3** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/114?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#114** <a href="https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/114?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#113** <a href="https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/113?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#112** <a href="https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dyc3 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by smcdonou02 — APPROVED** [review]
There are 2 points where wording is changed from “the system must be…” to the “the system should be…” is this intentional or should they all be “must be…”?

**Comment by dyc3** [comment]
### Merge activity

* **May 12, 3:49 PM EDT**: @dyc3 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/114).

**Comment by dyc3** [comment]
@smcdonou02 Yes, it's intentional. "Must" indicates an absolute. "Should" indicates that failing to meet the requirement doesn't render the entire project a failure.

**Pull request merged**
